#deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-app-deployment
  labels:
    app: my-nginx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-app
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      containers:
        # Our PHP-FPM application
        - image: lehoanggroup1487/rocky-nginx-php:1.0.9
          name: my-nginx-app-container
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-app-service
spec:
  selector:
    app: my-nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
